# Generated by Django 5.2.7 on 2025-11-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_theater', '0021_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
