# Generated by Django 5.2.7 on 2025-11-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_theater', '0023_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_bio',
            field=models.TextField(default=''),
        ),
    ]
