# Generated by Django 5.2.7 on 2025-11-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_theater', '0025_remove_comment_discussion_message_delete_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='images/lucky.jpg', upload_to='images/'),
        ),
    ]
